%Y

%% add MATPOWER paths
MfilePath = mfilename('fullpath');
[RootPath,~,~]  = fileparts(MfilePath);
cd(RootPath);
addpath( ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\lib', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\lib\t', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\data', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\most\lib', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\most\lib\t', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\mp-opt-model\lib', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\mp-opt-model\lib\t', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\mips\lib', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\mips\lib\t', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\mptest\lib', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\mptest\lib\t', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\maxloadlim', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\maxloadlim\tests', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\maxloadlim\examples', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\misc', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\reduction', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\sdp_pf', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\se', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\smartmarket', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\state_estimator', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\syngrid\lib', ...
    'C:\Users\yz7521\OneDrive - Imperial College London\BCU Code\BCU_3M9B\C1_Matpower\matpower7.1\extras\syngrid\lib\t', ...
    '-end' );
%%
addpath(genpath([RootPath,'/C1_Matpower']));
addpath(genpath([RootPath,'/B3_MM']));
